[package]
name = "vrypt"
version = "3.1.1"
edition = "2021"

[dependencies]
mio = { version = "0.8", features = ["net", "os-poll"] }
socket2 = { version = "0.5", features = ["all"] }

[profile.release]
lto = "thin"
codegen-units = 1
opt-level = 3
